version: '3'
# Define the services/containers to be run
services:
  myapp: #name of your service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database # link this service to the database service
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  database: # name of the service
    image: mongo # specify image to build container from

version: "3"

services:
  languagesapp:
    build: ./
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_NAME}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_DB: ${MONGO_DB}
    networks:
      - languages-network
    volumes:
      - .:/srv/app
    ports:
      - "3000:3000"

  db:
    image: mongo
    container_name: language_db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - languages-network
    volumes:
      - languages:/data/db
    ports:
      - "27017:27017"

networks:
  languages-network:
    driver: bridge

volumes:
  languages:
