version: "3.4"
services:
  app:
    build:
      context: ./
    command: node /srv/app/bin/www
    container_name: language_app
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PWD: ${MONGO_PWD}
      MONGO_DB: ${MONGO_DB}
    networks:
      - languages-network
    volumes:
      - .:/srv/app
    ports:
      - "3000:3000"

  db:
    image: mongo:latest
    container_name: language_db
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOTPWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_NON_ROOT_USERNAME: ${MONGO_USER}
      MONGO_NON_ROOT_PASSWORD: ${MONGO_PWD}
    networks:
      - languages-network
    volumes:
      - ./mongo_init/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - languages:/data/db
    ports:
      - "27017:27017"

networks:
  languages-network:
    driver: bridge

volumes:
  languages:
